version: '3'
services:
  hadoop-into:
    image: analyticalx/hadoop-into
    restart: always
    volumes:
      - ./analyticalx/files:/root/analyticalx/files
      - ./analyticalx/py:/root/analyticalx/py
      - ./analyticalx/web:/opt/analyticalx/web
    # command: bash /analyticalx/sh/start-into.sh
    ports:
    - "2222:22"
    - "5000:5000"
    - "8088:8088"
    - "50070:50070"
